Utils tests for testable utils (such as converters and parsers)
ITA-Dnipro/BackEndMonitoring pull request #78
Opened 2021-02-18 15:34 UTC by Chupakabra0

Works just for Windows, Linux update will be added soon

2021-02-18 16:47 UTC, VytalyGorbatov requested changes

2021-02-18 16:47 UTC, VytalyGorbatov commented on UtilsTests/UtilsTests.vcxproj.filters
> +      <Filter>Исходные файлы</Filter>
Please, remove all cyrillyc words(Rename filters)

2021-02-18 17:24 UTC, Chupakabra0 commented on UtilsTests/UtilsTests.vcxproj.filters
> +      <Filter>Исходные файлы</Filter>
Fixed

2021-02-19 12:56 UTC, AntonVoytov approved these changes

2021-02-21 12:54 UTC, VytalyGorbatov approved these changes

2021-02-21 13:12 UTC, merged